package io.muic.ooc.pos;

import io.muic.ooc.pos.MenuItem.MenuRepository;
import io.muic.ooc.pos.Order.OrderRepository;
import io.muic.ooc.pos.Record.RecordModel;
import io.muic.ooc.pos.Record.RecordRepository;
import io.muic.ooc.pos.Table.TableCheck;
import io.muic.ooc.pos.Table.TableCheckRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;

//import hello.User;
//import hello.UserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;

    @Autowired
    private MenuRepository menuRepository;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private TableCheckRepository tableCheckRepository;

    @Autowired
    private RecordRepository recordRepository;















}
