package io.muic.ooc.pos;

import io.muic.ooc.pos.MenuItem.Menu;
import io.muic.ooc.pos.MenuItem.MenuRepository;
import io.muic.ooc.pos.Order.Order;
import io.muic.ooc.pos.Order.OrderRepository;
import io.muic.ooc.pos.Record.RecordModel;
import io.muic.ooc.pos.Record.RecordRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

//import hello.User;
//import hello.UserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;

    @Autowired
    private MenuRepository menuRepository;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private TableCheckRepository tableCheckRepository;

    @Autowired
    private RecordRepository recordRepository;



//    @CrossOrigin(origins = "http://localhost:3000")
//    @RequestMapping(value = "/order", method =  RequestMethod.POST)
//    public ResponseEntity<UserDto> update(@RequestBody UserDto user){
//        User n = new User();
//        n.setName(user.getName());
//        n.setEmail(user.getEmail());
//
//        userRepository.save(n);
//        System.out.println("orderrrrrr");
//
//        return new ResponseEntity<UserDto>(user, HttpStatus.OK);
//    }


    // @CrossOrigin(origins = "http://localhost:3000")
//    @RequestMapping(value = "/order_to_kitchen", method =  RequestMethod.POST)
//    public ResponseEntity<Order> update_2(@RequestBody Order order){
//        Order n = new Order();
//        n.setName(order.getName());
//        n.setTableNumber(order.getTableNumber());
//        n.setCurrentStatus(order.getCurrentStatus());
//        n.setKindOf(order.getKindOf());
//
//        orderRepository.save(n);
//
//        System.out.println("orderrrrrr kitchen");
//
//        return new ResponseEntity<Order>(order, HttpStatus.OK);
//    }

    // @CrossOrigin(origins = "http://localhost:3000")
    @RequestMapping(value = "/putin_table", method =  RequestMethod.POST)
    public ResponseEntity<TableCheck> check (@RequestBody TableCheck tableCheck){
        TableCheck m = new TableCheck();
        m.setStatusCheck(tableCheck.getStatusCheck());
        m.setTableNumber(tableCheck.getTableNumber());
//        n.setCurrentStatus(order.getCurrentStatus());
//        n.setKindOf(order.getKindOf());

        tableCheckRepository.save(m);

        System.out.println("Check table.");

        return new ResponseEntity<TableCheck>(tableCheck, HttpStatus.OK);
    }

    @GetMapping(path="/get_table")
    public @ResponseBody Iterable<TableCheck> getAllTables() {
        // This returns a JSON or XML with the users
        return tableCheckRepository.findByStatusCheck(Boolean.TRUE);
    }

    @GetMapping(path="/show_cashier")
    public @ResponseBody Iterable<RecordModel> getAllTables_2() {
        // This returns a JSON or XML with the users
//        return recordRepository.findByStatusAndStatus("unpaid","pending");
        return recordRepository.findByStatusOrStatus("unpaid","pending");
    }

    @GetMapping(path="/get_table_3")
    public @ResponseBody RecordModel getAllTables_3(@RequestParam Long recid) {
        // This returns a JSON or XML with the users
        return recordRepository.findOneById(recid);
    }




//    @GetMapping(path="/each_table")
//    public @ResponseBody Iterable<Order> eachTable (@RequestParam Integer table) {
//        // This returns a JSON or XML with the users
//        System.out.println("get order");
//        return orderRepository.findByTableNumber(table);
//    }

//    @GetMapping(path="/each_kitchen")
//    public @ResponseBody Iterable<Order> eachKitchen (@RequestParam Integer kindof) {
//        // This returns a JSON or XML with the users
//        System.out.println("get each kitchen");
//        return orderRepository.findByCategoryType(kindof);
//    }

    // @CrossOrigin(origins = "http://localhost:3000")
    @GetMapping(path="/status_table")
    public @ResponseBody Boolean eachStatus (@RequestParam Integer table) {
        // This returns a JSON or XML with the users
        List<TableCheck> all = tableCheckRepository.findByTableNumber(table);
        boolean ans;
        System.out.println("get order");
//        System.out.println(tableCheckRepository.findByTableNumber(6));
        if (!tableCheckRepository.exists(table)){
            System.out.println(!tableCheckRepository.exists(table));
            TableCheck tableCheck_2 = new TableCheck();
            tableCheck_2.setStatusCheck(Boolean.TRUE);
            tableCheck_2.setTableNumber(table);
            tableCheckRepository.save(tableCheck_2);
            return Boolean.TRUE;
        }
        else if (all.get(0).getStatusCheck().equals(false)){
            TableCheck tableCheck = tableCheckRepository.findOne(table);
            tableCheck.setStatusCheck(Boolean.TRUE);
            tableCheckRepository.save(tableCheck);
            return Boolean.TRUE;
        }
        else{
            return Boolean.FALSE;
        }
    }


    @GetMapping(path="/all_table_true")
    public @ResponseBody Iterable<TableCheck> getAllTable() {
        // This returns a JSON or XML with the users
        return tableCheckRepository.findAllByStatusCheck(Boolean.TRUE);
    }

    @GetMapping(path="/check_login")
    public @ResponseBody Boolean checkLogin (@RequestParam Integer table){
        TableCheck tableCheck = tableCheckRepository.findOne(table);
        return tableCheck.getStatusCheck();
    }






    @PutMapping(path="/table_logout") // Map ONLY GET Requests
    public @ResponseBody String logout (@RequestParam Integer table_num) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        TableCheck order_1 = tableCheckRepository.findOne(table_num);
        order_1.setStatusCheck(Boolean.FALSE);
        tableCheckRepository.save(order_1);
        System.out.println("Logout");
        return "Saved";
    }








//    @CrossOrigin(origins = "http://localhost:3000")
//    @RequestMapping(value = "/update_to_kitchen", method =  RequestMethod.PUT)
//    public ResponseEntity<Order> update_3(@RequestBody Order order){
//        Order m = new Order();
//        Long curId = m.getId();
//        String curSta = m.getCurrentStatus();
//
//        Order order_1 = orderRepository.findOne(curId);
//
//        order_1.setCurrentStatus(curSta);
//
//
//        Order updateOrder = orderRepository.save(order_1);
//
//        return new ResponseEntity<Order>(updateOrder, HttpStatus.OK);
//    }

//    @RequestMapping(value = "/update_to_kitchen", method =  RequestMethod.PUT)
//    @ResponseBody
//    public String updateStatus(long id, String currentStatus){
//        try {
//            Order order = orderRepository.findOne(id);
//            order.
//
//
//        }
//        catch (Exception ex) {
//            return "Error updating the user: " + ex.toString();
//        }
//        return "User successfully updated!";
//
//    }


}
